version: '3.5'

services:
#    nginx:
#        build: ./docker/images/nginx
#        ports:
#            - "8089:80"
#            # - "443:443"
#        volumes:
#            # - ./docker/hosts:/etc/nginx/conf.d
#            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
#            - ./application:/var/www/html
#            - ./logs:/var/log/nginx
#            - ./letsencrypt:/etc/letsencrypt
#            - ./acme-challenge:/var/lib/certbot/.well-known/acme-challenge
#        networks:
#            - cluster
#        links:
#            - app
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/app
        ports:
            - "80:8000"
        links:
            - postgresql
            - redis
        networks:
            - cluster
#        working_dir: /var/www/html
#        volumes:
#            - ./application:/var/www/html
    postgresql:
        image: postgres:9.6.21-alpine
        ports:
            - "5431:5432"
        networks:
            - cluster
        volumes:
            - ./database:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: clever

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - cluster
#    npm:
#        build: ./docker/images/npm
#        working_dir: /var/www/html
##        command: npm start
#        ports:
#            - "3000:3000"
#        networks:
#            - cluster
#        environment:
networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

